// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { ImagesService } from './services/images';
import { BreedsService } from './services/breeds';
import { FactsService } from './services/facts';
import { FavouritesService } from './services/favourites';
import { VotesService } from './services/votes';
import { WebhooksService } from './services/webhooks';

export * from './services/images';
export * from './services/breeds';
export * from './services/facts';
export * from './services/favourites';
export * from './services/votes';
export * from './services/webhooks';

export * from './http';
export { Environment } from './http/environment';

export class Cats {
  public readonly images: ImagesService;

  public readonly breeds: BreedsService;

  public readonly facts: FactsService;

  public readonly favourites: FavouritesService;

  public readonly votes: VotesService;

  public readonly webhooks: WebhooksService;

  constructor(public config: SdkConfig) {
    this.images = new ImagesService(this.config);

    this.breeds = new BreedsService(this.config);

    this.facts = new FactsService(this.config);

    this.favourites = new FavouritesService(this.config);

    this.votes = new VotesService(this.config);

    this.webhooks = new WebhooksService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.images.baseUrl = baseUrl;
    this.breeds.baseUrl = baseUrl;
    this.facts.baseUrl = baseUrl;
    this.favourites.baseUrl = baseUrl;
    this.votes.baseUrl = baseUrl;
    this.webhooks.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.images.baseUrl = environment;
    this.breeds.baseUrl = environment;
    this.facts.baseUrl = environment;
    this.favourites.baseUrl = environment;
    this.votes.baseUrl = environment;
    this.webhooks.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.images.timeoutMs = timeoutMs;
    this.breeds.timeoutMs = timeoutMs;
    this.facts.timeoutMs = timeoutMs;
    this.favourites.timeoutMs = timeoutMs;
    this.votes.timeoutMs = timeoutMs;
    this.webhooks.timeoutMs = timeoutMs;
  }

  set token(token: string) {
    this.images.token = token;
    this.breeds.token = token;
    this.facts.token = token;
    this.favourites.token = token;
    this.votes.token = token;
    this.webhooks.token = token;
  }

  set apiKey(apiKey: string) {
    this.images.apiKey = apiKey;
    this.breeds.apiKey = apiKey;
    this.facts.apiKey = apiKey;
    this.favourites.apiKey = apiKey;
    this.votes.apiKey = apiKey;
    this.webhooks.apiKey = apiKey;
  }

  set apiKeyHeader(apiKeyHeader: string) {
    this.images.apiKeyHeader = apiKeyHeader;
    this.breeds.apiKeyHeader = apiKeyHeader;
    this.facts.apiKeyHeader = apiKeyHeader;
    this.favourites.apiKeyHeader = apiKeyHeader;
    this.votes.apiKeyHeader = apiKeyHeader;
    this.webhooks.apiKeyHeader = apiKeyHeader;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
