// This file was generated by liblab | https://liblab.com/

import { Cats } from 'cats';

(async () => {
  const cats = new Cats({
    token: 'YOUR_TOKEN',
  });

  const { data } = await cats.images.imagesListSearchOrRandom({
    size: 'size',
    mimeTypes: 'mime_types',
    format: 'format',
    hasBreeds: true,
    order: 'order',
    page: 2,
    limit: 9,
    contentType: 'Content-Type',
    xApiKey: 'x-api-key',
  });

  console.log(data);
})();
