// This file was generated by liblab | https://liblab.com/

export interface GetVotesParams {
  xApiKey: string;
  contentType?: string;
}

export interface CreateVotesParams {
  xApiKey: string;
  contentType?: string;
}

export interface GetVotesByVoteIdParams {
  xApiKey: string;
  contentType?: string;
}

export interface DeleteVoteByVoteIdParams {
  xApiKey: string;
  contentType?: string;
}
