// This file was generated by liblab | https://liblab.com/

export interface ImagesListSearchOrRandomParams {
  size?: string;
  mimeTypes?: string;
  format?: string;
  hasBreeds?: boolean;
  order?: string;
  page?: number;
  limit?: number;
  contentType?: string;
  xApiKey?: string;
}

export interface GetImagesBkIEhN3pGParams {
  xApiKey?: string;
}

export interface GetImagesParams {
  xApiKey: string;
  limit?: number;
  page?: number;
  order?: string;
  contentType?: string;
}

export interface CreateImagesUploadParams {
  xApiKey: string;
  contentType?: string;
}

export interface DeleteImagesByImageIdParams {
  contentType?: string;
  xApiKey?: string;
}

export interface GetImagesByImageIdBreedsParams {
  contentType?: string;
}

export interface CreateImagesByImageIdBreedsParams {
  xApiKey: string;
  contentType?: string;
}

export interface DeleteImagesByImageIdBreedsByBreedIdParams {
  xApiKey: string;
  contentType?: string;
}
