// This file was generated by liblab | https://liblab.com/

export interface GetBreedsParams {
  xApiKey: string;
  limit?: number;
  page?: number;
  contentType?: string;
}

export interface GetBreedsByBreedIdParams {
  contentType?: string;
}

export interface GetBreedsSearchParams {
  q?: string;
  attachImage?: number;
}
