// This file was generated by liblab | https://liblab.com/

export interface GetFavouritesParams {
  xApiKey: string;
  contentType?: string;
}

export interface CreateFavouritesParams {
  xApiKey: string;
  contentType?: string;
}

export interface GetFavouritesByFavouriteIdParams {
  xApiKey: string;
  contentType?: string;
}

export interface DeleteFavouritesByFavouriteIdParams {
  xApiKey: string;
  contentType?: string;
}
